spring:
  application:
    name: potenday-server
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---
