name: Deploy to NCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 코드 불러오기
        uses: actions/checkout@v4

      - name: Docker Buildx 세팅하기
        uses: docker/setup-buildx-action@v3

      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 설정파일(application.yml) 디렉토리 만들기 & 주입
        run: |
          mkdir -p ./backend/src/main/resources/
          echo "${{ secrets.APPLICATION_YML }}" > ./backend/src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./backend/src/main/resources/application-dev.yml

      - name: Docker 이미지 빌드 및 DockerHub 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rudalsss/potenday:latest

      - name: Ncloud 서버 SSH 접속 후 Docker 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.NCLOUD_HOST }}
          username: ${{ secrets.NCLOUD_USER }}
          key: ${{ secrets.NCLOUD_SSH_KEY }}
          script: |
            docker pull rudalsss/potenday:latest
            docker stop potenday-server || true
            docker rm potenday-server || true
            docker run -d --name potenday-server -p 8080:8080 rudalsss/potenday:latest
